[package]
name = "auto_builder_derive"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Macros for generating a 'safe' builder"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
darling = "0.20.5"
proc-macro2 = "1.0.78"
